[package]
name = "fd-netctl"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
ctrlc = { version = "3.5", features = ["termination"] }
libc = "0.2"
nfq = "0.2.5"
reqwest = { version = "0.12", default-features = false, features = ["blocking", "json", "rustls-tls"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
toml = "0.5"
